version: "3.9"

services:
  api:
    build: .
    container_name: fraud_api
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: fraud_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: fraud_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:
  prometheus_data: